environment:
  ELM_VERSION: "0.18.0"
  matrix:
  - nodejs_version: "6.9"

platform:
  - x64

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - npm install -g elm@%ELM_VERSION%
  - npm install

build: off

build_script:
  - npm run build-ci

test_script:
  - npm run test-console
